import os
import subprocess
from aws_cdk import (
    Aws,
    aws_ec2,
    aws_route53,
    CfnCondition,
    CfnMapping,
    CfnOutput,
    CfnParameter,
    Fn,
    Stack,
    Tags
)
from constructs import Construct

from oe_patterns_cdk_common.asg import Asg
from oe_patterns_cdk_common.vpc import Vpc

TWO_YEARS_IN_DAYS=731
if 'TEMPLATE_VERSION' in os.environ:
    template_version = os.environ['TEMPLATE_VERSION']
else:
    try:
        template_version = subprocess.check_output(["git", "describe"]).strip().decode('ascii')
    except:
        template_version = "CICD"

# When making a new development AMI:
# 1) $ ave oe-patterns-dev make ami-ec2-build
# 2) $ ave oe-patterns-dev make AMI_ID=ami-fromstep1 ami-ec2-copy
# 3) Copy the code that copy-image generates below

# AMI list generated by:
# make TEMPLATE_VERSION=3.0.0 ami-ec2-build
# on Tue Oct  3 00:23:36 UTC 2023.
AMI_ID="ami-01bc5c1468f98283a"
AMI_NAME="ordinary-experts-patterns-jitsi-3.0.0-20231003-1214"
generated_ami_ids = {
    "ap-northeast-1": "ami-XXXXXXXXXXXXXXXXX",
    "ap-northeast-2": "ami-XXXXXXXXXXXXXXXXX",
    "ap-south-1": "ami-XXXXXXXXXXXXXXXXX",
    "ap-southeast-1": "ami-XXXXXXXXXXXXXXXXX",
    "ap-southeast-2": "ami-XXXXXXXXXXXXXXXXX",
    "ca-central-1": "ami-XXXXXXXXXXXXXXXXX",
    "eu-central-1": "ami-XXXXXXXXXXXXXXXXX",
    "eu-north-1": "ami-XXXXXXXXXXXXXXXXX",
    "eu-west-1": "ami-XXXXXXXXXXXXXXXXX",
    "eu-west-2": "ami-XXXXXXXXXXXXXXXXX",
    "eu-west-3": "ami-XXXXXXXXXXXXXXXXX",
    "sa-east-1": "ami-XXXXXXXXXXXXXXXXX",
    "us-east-2": "ami-XXXXXXXXXXXXXXXXX",
    "us-west-1": "ami-XXXXXXXXXXXXXXXXX",
    "us-west-2": "ami-XXXXXXXXXXXXXXXXX",
    "us-east-1": "ami-01bc5c1468f98283a"
}
# End generated code block.

# Sanity check: if this fails then make copy-image needs to be run...
assert AMI_ID == generated_ami_ids["us-east-1"]

class JitsiStack(Stack):

    def __init__(self, scope: Construct, id: str, **kwargs) -> None:
        super().__init__(scope, id, **kwargs)

        ami_mapping={
            "AMI": {
                "AMI": AMI_NAME
            }
        }
        for region in generated_ami_ids.keys():
            ami_mapping[region] = { "AMI": generated_ami_ids[region] }
        CfnMapping(
            self,
            "AWSAMIRegionMap",
            mapping=ami_mapping
        )

        #
        # PARAMETERS
        #

        cidr_block_param = CfnParameter(
            self,
            "IngressCidrBlock",
            allowed_pattern="((\d{1,3})\.){3}\d{1,3}/\d{1,2}",
            default="0.0.0.0/0",
            description="Required: A CIDR block to restrict access to the Jitsi application. Leave as 0.0.0.0/0 to allow public access from internet."
        )
        jitsi_hostname_param = CfnParameter(
            self,
            "JitsiHostname",
            description="Required: The hostname to access Jitsi. E.G. 'jitsi.internal.mycompany.com'"
        )
        jitsi_interface_app_name_param = CfnParameter(
            self,
            "JitsiInterfaceAppName",
            default="Jitsi Meet",
            description="Optional: Customize the app name on the Jitsi interface."
        )
        jitsi_interface_default_remote_display_name_param = CfnParameter(
            self,
            "JitsiInterfaceDefaultRemoteDisplayName",
            default="Fellow Jitster",
            description="Optional: Customize the default display name for Jitsi users."
        )
        jitsi_interface_native_app_name_param = CfnParameter(
            self,
            "JitsiInterfaceNativeAppName",
            default="Jitsi Meet",
            description="Optional: Customize the native app name on the Jitsi interface."
        )
        jitsi_interface_show_brand_watermark_param = CfnParameter(
            self,
            "JitsiInterfaceShowBrandWatermark",
            allowed_values=[ "true", "false" ],
            default="true",
            description="Optional: Display the watermark logo image in the upper left corner."
        )
        jitsi_interface_show_watermark_for_guests_param = CfnParameter(
            self,
            "JitsiInterfaceShowWatermarkForGuests",
            allowed_values=[ "true", "false" ],
            default="true",
            description="Optional: Display the watermark logo image in the upper left corner for guest users. This can be set to override the general setting behavior for guest users."
        )
        jitsi_interface_brand_watermark_param = CfnParameter(
            self,
            "JitsiInterfaceBrandWatermark",
            default="",
            description="Optional: Provide a URL to a PNG image to be used as the brand watermark logo image in the upper right corner. File should be publically available for download."
        )
        jitsi_interface_brand_watermark_link_param = CfnParameter(
            self,
            "JitsiInterfaceBrandWatermarkLink",
            default="https://jitsi.org",
            description="Optional: Provide a link destination for the brand watermark logo image in the upper right corner."
        )
        jitsi_interface_watermark_param = CfnParameter(
            self,
            "JitsiInterfaceWatermark",
            default="",
            description="Optional: Provide a URL to a PNG image to be used as the watermark logo image in the upper left corner. File should be publically available for download."
        )
        jitsi_interface_watermark_link_param = CfnParameter(
            self,
            "JitsiInterfaceWatermarkLink",
            default="https://jitsi.org",
            description="Optional: Provide a link destination for the Jitsi watermark logo image in the upper left corner."
        )
        route_53_hosted_zone_name_param = CfnParameter(
            self,
            "Route53HostedZoneName",
            description="Required: Route 53 Hosted Zone name in which a DNS record will be created by this template. Must already exist and be the domain part of the Jitsi Hostname parameter, without trailing dot. E.G. 'internal.mycompany.com'"
        )

        notification_email_param = CfnParameter(
            self,
            "NotificationEmail",
            default="",
            description="Optional: Specify an email address to get emails about deploys, Let's Encrypt, and other system events."
        )

        #
        # CONDITIONS
        #

        notification_email_exists_condition = CfnCondition(
            self,
            "NotificationEmailExistsCondition",
            expression=Fn.condition_not(Fn.condition_equals(notification_email_param.value, ""))
        )

        #
        # RESOURCES
        #

        # vpc
        vpc = Vpc(
            self,
            "Vpc"
        )

        # ec2
        jitsi_sg = aws_ec2.CfnSecurityGroup(
            self,
            "JitsiSg",
            group_description="Jitsi security group",
            vpc_id=vpc.id()
        )

        eip = aws_ec2.CfnEIP(
            self,
            "Eip",
            domain="vpc"
        )
        Tags.of(eip).add("Name", "{}/Eip".format(Aws.STACK_NAME))

        with open("jitsi/user_data.sh") as f:
            user_data = f.read()
        asg = Asg(
            self,
            "Asg",
            allow_associate_address=True,
            default_instance_type="t3.xlarge",
            singleton=True,
            use_graviton=False,
            user_data_contents=user_data,
            user_data_variables={
                "JitsiHostname": jitsi_hostname_param.value_as_string,
                "JitsiPublicIP": eip.ref,
                "LetsEncryptCertificateEmail": notification_email_param.value_as_string
            },
            use_public_subnets=True,
            vpc=vpc
        )

        jitsi_http_ingress = aws_ec2.CfnSecurityGroupIngress(
            self,
            "JitsiHttpSgIngress",
            cidr_ip=cidr_block_param.value_as_string,
            from_port=80,
            group_id=asg.sg.ref,
            ip_protocol="tcp",
            to_port=80
        )
        jitsi_https_ingress = aws_ec2.CfnSecurityGroupIngress(
            self,
            "JitsiHttpsSgIngress",
            cidr_ip=cidr_block_param.value_as_string,
            from_port=443,
            group_id=asg.sg.ref,
            ip_protocol="tcp",
            to_port=443
        )
        jitsi_fallback_network_audio_video_ingress = aws_ec2.CfnSecurityGroupIngress(
            self,
            "JitsiFallbackNetworkAudioVideoSgIngress",
            cidr_ip=cidr_block_param.value_as_string,
            from_port=4443,
            group_id=asg.sg.ref,
            ip_protocol="tcp",
            to_port=4443
        )
        jitsi_general_network_audio_video_ingress = aws_ec2.CfnSecurityGroupIngress(
            self,
            "JitsiGeneralNetworkAudioVideoSgIngress",
            cidr_ip=cidr_block_param.value_as_string,
            from_port=10000,
            group_id=asg.sg.ref,
            ip_protocol="udp",
            to_port=10000
        )

        record_set = aws_route53.CfnRecordSet(
            self,
            "RecordSet",
            hosted_zone_name=f"{route_53_hosted_zone_name_param.value_as_string}.",
            name=jitsi_hostname_param.value_as_string,
            resource_records=[ eip.ref ],
            type="A"
        )
        record_set.add_property_override("TTL", 60)

        # AWS::CloudFormation::Interface
        self.template_options.metadata = {
            "OE::Patterns::TemplateVersion": template_version,
            "AWS::CloudFormation::Interface": {
                "ParameterGroups": [
                    {
                        "Label": {
                            "default": "Infrastructure Config"
                        },
                        "Parameters": [
                            jitsi_hostname_param.logical_id,
                            route_53_hosted_zone_name_param.logical_id,
                            cidr_block_param.logical_id,
                            notification_email_param.logical_id
                        ]
                    },
                    {
                        "Label": {
                            "default": "Jitsi Config"
                        },
                        "Parameters": [
                            jitsi_interface_app_name_param.logical_id,
                            jitsi_interface_default_remote_display_name_param.logical_id,
                            jitsi_interface_native_app_name_param.logical_id,
                            jitsi_interface_show_brand_watermark_param.logical_id,
                            jitsi_interface_show_watermark_for_guests_param.logical_id,
                            jitsi_interface_brand_watermark_param.logical_id,
                            jitsi_interface_brand_watermark_link_param.logical_id,
                            jitsi_interface_watermark_param.logical_id,
                            jitsi_interface_watermark_link_param.logical_id,
                        ]
                    },
                    *asg.metadata_parameter_group(),
                    *vpc.metadata_parameter_group()
                ],
                "ParameterLabels": {
                    notification_email_param.logical_id: {
                        "default": "Notification Email"
                    },
                    cidr_block_param.logical_id: {
                        "default": "Ingress CIDR Block"
                    },
                    jitsi_hostname_param.logical_id: {
                        "default": "Jitsi Hostname"
                    },
                    jitsi_interface_app_name_param.logical_id: {
                        "default": "Jitsi Interface App Name"
                    },
                    jitsi_interface_default_remote_display_name_param.logical_id: {
                        "default": "Jitsi Interface Default Remote Display Name"
                    },
                    jitsi_interface_native_app_name_param.logical_id: {
                        "default": "Jitsi Interface Native App Name"
                    },
                    jitsi_interface_show_brand_watermark_param.logical_id: {
                        "default": "Jitsi Interface Show Watermark"
                    },
                    jitsi_interface_show_watermark_for_guests_param.logical_id: {
                        "default": "Jitsi Interface Show Watermark For Guests"
                    },
                    jitsi_interface_brand_watermark_param.logical_id: {
                        "default": "Jitsi Interface Watermark"
                    },
                    jitsi_interface_brand_watermark_link_param.logical_id: {
                        "default": "Jitsi Interface Watermark Link"
                    },
                    jitsi_interface_watermark_param.logical_id: {
                        "default": "Jitsi Interface Watermark"
                    },
                    jitsi_interface_watermark_link_param.logical_id: {
                        "default": "Jitsi Interface Watermark Link"
                    },
                    route_53_hosted_zone_name_param.logical_id: {
                        "default": "AWS Route 53 Hosted Zone Name"
                    },
                    **asg.metadata_parameter_labels(),
                    **vpc.metadata_parameter_labels()
                }
            }
        }

        #
        # OUTPUTS
        #

        endpoint_output = CfnOutput(
            self,
            "JitsiUrl",
            description="The URL for the Jitsi instance.",
            value=Fn.join("", ["https://", jitsi_hostname_param.value_as_string])
        )
