---
"Product ID": "OE_PATTERNS_JITSI_{{version}}"
"Product Code": "OE_PATTERNS_JITSI_{{version}}"
"Accessibility": "Production-Ready Jitsi Meet on AWS: Current Environment: Ubuntu 18.04.4 LTS, Apache 2.4.29, Jitsi version 2.0.4966-1"
"SKU": "OE_PATTERNS_JITSI_{{version}}"
"Software by": "Ordinary Experts"
"Title": "Ordinary Experts Jitsi Pattern"
"Short Description": "The Ordinary Experts Jitsi Pattern is an open-source AWS CloudFormation template + custom AMI that offers an easy-to-install AWS infrastructure solution for quickly deploying Jitsi Meet, using AWS best practices."
"Full Description": "The Ordinary Experts Jitsi Pattern is an open-source AWS CloudFormation template that offers an easy-to-install AWS infrastructure solution for quickly deploying Jitsi Meet, using AWS best practices. The template makes it easy to spin up a production-ready, full-feature infrastructure ready to host Jitsi Meet in the AWS cloud.

This template allows customization of the Jitsi Meet interface and allows Jitsi Meet to be locked down to a range of IPs. The Jitsi Meet server is created in an AutoScaling group for high-availability."
"Highlight1": "Launch a full-featured Jitsi Meet server in minutes."
"Highlight2": "Lock down access to a range of IP addresses."
"Highlight3": "Customize the Jitsi Meet interface with your logo and link."
"Product Category1": "Application Stacks"
"Product Category2": "Application Development"
"Product Category3": "Content Management"
"Search Keywords": "jitsi, meet, video, conference, zoom, chime"
"Resource1_Name": "Ordinary Experts Product Page"
"Resource1_URL": "https://ordinaryexperts.com/products/jitsi-pattern/"
"Resource2_Name": "Github Source Code and Documentation"
"Resource2_URL": "https://github.com/ordinaryexperts/aws-marketplace-oe-patterns-jitsi/tree/main"
"Resource3_Name": "Jitsi Homepage"
"Resource3_URL": "https://jitsi.org/"
"Image URL": "https://ordinaryexperts.com/img/services/oe_jitsi_patterns_topology_diagram.png"
"Product Video": ""
"Support Offered": "TRUE"
"Support Information": "https://ordinaryexperts.com/products/jitsi-pattern/"
"Support Detail": "Email support offered with subscription."
"Refund and Cancelation Policy": "We do not currently support refunds, but you can cancel at any time."
"Type": "AMI"
"us-east-1 AMI ID": "{{ami}}" # final ami id
"AMI Virtualization Type": "HVM"
"Architecture": "x86_64"
"AFI": ""
"Operating System": "Ubuntu"
"Operating System Version": "18.04"
"Operating System Username": "ubuntu"
"PIOPS Total": ""
"AWS Services Required": "Amazon EC2, Amazon VPC, Amazon IAM, Amazon SNS, Amazon CloudFormation"
"3rd Party Software Included": "Ubuntu packages: curl git jq ntp unzip vim wget zip python-pip collectd ruby binutils git apache2 jitsi-meet, AWS CloudFormation utilities, AWS CLI, AWS CloudWatch agent."
"Version Title": "{{version}}"
"Release Notes": "See GitHub project for release notes."
"Upgrade Instructions": "Re-run the stack to apply new infrastructure changes."
"Product Access Instructions": "Run the stack. If not using the HostedZone Route53 integration, then make sure to add the appropriate DNS record so the Let's Encrypt cert can be created."
"Endpoint URL Protocol": "http/https/tcp/udp"
"Endpoint URL Port": "80/443/4443/10000"
"Endpoint URL Relative URL": "/"
"Countries to include": ""
"Countries to exclude": ""
# EULA: https://docs.aws.amazon.com/marketplace/latest/userguide/standardized-license-terms.html
"End User License Agreement URL": "https://s3.amazonaws.com/EULA/Standard+Contract+for+AWS+Marketplace+2019-04-24.pdf"
# region availability fields are here, i.e. "me-south-1 Availability"
"Make available in all future U.S. regions": "FALSE"
"Make available in all future non-U.S. regions": "FALSE"
"Recommended Instance Type": "m5.xlarge"
"Make available for all future instance types": "FALSE"
# instance availability fields are here, i.e. "z1d.12xlarge Availability"
"Pricing Model": "Hourly_Annual"
"Product Tax Code": "A_GEN_NOTAX"
"BYOL URL": ""
"Free Trial Instance Count": "1"
"Free Trial Duration": "5"
# instance Hourly Price fields are here, i.e. "z1d.12xlarge Hourly Price"
"Monthly Price": ""
# instance Annual Price fields are here, i.e. "z1d.12xlarge Annual Price"
"Security Group Rule 1": ""
"Security Group Rule 2": ""
"Security Group Rule 3": ""
"Security Group Rule 4": ""
"Security Group Rule 5": ""
"Security Group Rule 6": ""
"Security Group Rule 7": ""
"Security Group Rule 8": ""
"Security Group Rule 9": ""
"Security Group Rule 10": ""
"Security Group Rule 11": ""
"Security Group Rule 12": ""
"FCP Category": ""
"FCP Unit": ""
"FCP Dimension1 Name": ""
"FCP Dimension1 Description": ""
"FCP Dimension1 Rate": ""
"FCP Dimension2 Name": ""
"FCP Dimension2 Description": ""
"FCP Dimension2 Rate": ""
"FCP Dimension3 Name": ""
"FCP Dimension3 Description": ""
"FCP Dimension3 Rate": ""
"FCP Dimension4 Name": ""
"FCP Dimension4 Description": ""
"FCP Dimension4 Rate": ""
"FCP Dimension5 Name": ""
"FCP Dimension5 Description": ""
"FCP Dimension5 Rate": ""
"FCP Dimension6 Name": ""
"FCP Dimension6 Description": ""
"FCP Dimension6 Rate": ""
"FCP Dimension7 Name": ""
"FCP Dimension7 Description": ""
"FCP Dimension7 Rate": ""
"FCP Dimension8 Name": ""
"FCP Dimension8 Description": ""
"FCP Dimension8 Rate": ""
"FCP Dimension9 Name": ""
"FCP Dimension9 Description": ""
"FCP Dimension9 Rate": ""
"FCP Dimension10 Name": ""
"FCP Dimension10 Description": ""
"FCP Dimension10 Rate": ""
"FCP Dimension11 Name": ""
"FCP Dimension11 Description": ""
"FCP Dimension11 Rate": ""
"FCP Dimension12 Name": ""
"FCP Dimension12 Description": ""
"FCP Dimension12 Rate": ""
"FCP Dimension13 Name": ""
"FCP Dimension13 Description": ""
"FCP Dimension13 Rate": ""
"FCP Dimension14 Name": ""
"FCP Dimension14 Description": ""
"FCP Dimension14 Rate": ""
"FCP Dimension15 Name": ""
"FCP Dimension15 Description": ""
"FCP Dimension15 Rate": ""
"FCP Dimension16 Name": ""
"FCP Dimension16 Description": ""
"FCP Dimension16 Rate": ""
"FCP Dimension17 Name": ""
"FCP Dimension17 Description": ""
"FCP Dimension17 Rate": ""
"FCP Dimension18 Name": ""
"FCP Dimension18 Description": ""
"FCP Dimension18 Rate": ""
"FCP Dimension19 Name": ""
"FCP Dimension19 Description": ""
"FCP Dimension19 Rate": ""
"FCP Dimension20 Name": ""
"FCP Dimension20 Description": ""
"FCP Dimension20 Rate": ""
"FCP Dimension21 Name": ""
"FCP Dimension21 Description": ""
"FCP Dimension21 Rate": ""
"FCP Dimension22 Name": ""
"FCP Dimension22 Description": ""
"FCP Dimension22 Rate": ""
"FCP Dimension23 Name": ""
"FCP Dimension23 Description": ""
"FCP Dimension23 Rate": ""
"FCP Dimension24 Name": ""
"FCP Dimension24 Description": ""
"FCP Dimension24 Rate": ""
"Clusters and AWS Resources Topology 1: Title": "Ordinary Experts Jitsi Pattern"
"Clusters and AWS Resources Topology 1: AWS Calculator Link": "https://calculator.aws/#/estimate?id=1459d4bc50bcac9f37ced765f049b2b273885c76"
"Clusters and AWS Resources Topology 1: Short Description": "Ordinary Experts Jitsi Pattern AWS Architecture Diagram"
"Clusters and AWS Resources Topology 1: Long Description": "The Ordinary Experts Jitsi Patterns AWS Architecture Diagram shows the total flow of services from when the developer updates the project code to when the customer accesses the Jitsi Meet application. The diagram shows the following AWS Services: Amazon Elastic Compute Cloud (Amazon EC2), Amazon Virtual Public Cloud (Amazon VPC), and Amazon CloudWatch Logs."
"Clusters and AWS Resources Topology 1: CloudFormation Template URL": "https://ordinary-experts-aws-marketplace-drupal-pattern-artifacts.s3.amazonaws.com/jitsi/{{version}}/template.yaml"
"Clusters and AWS Resources Topology 1: Architecture Diagram URL": "https://ordinaryexperts.com/img/services/oe_jitsi_patterns_topology_diagram.png"
"Clusters and AWS Resources Topology 2: Title": ""
"Clusters and AWS Resources Topology 2: AWS Calculator Link": ""
"Clusters and AWS Resources Topology 2: Short Description": ""
"Clusters and AWS Resources Topology 2: Long Description": ""
"Clusters and AWS Resources Topology 2: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 2: Architecture Diagram URL": ""
"Clusters and AWS Resources Topology 3: Title": ""
"Clusters and AWS Resources Topology 3: AWS Calculator Link": ""
"Clusters and AWS Resources Topology 3: Short Description": ""
"Clusters and AWS Resources Topology 3: Long Description": ""
"Clusters and AWS Resources Topology 3: CloudFormation Template URL": ""
"Clusters and AWS Resources Topology 3: Architecture Diagram URL": ""
